services:
  postgre:
    image: postgres:16-alpine
    container_name: postgre
    networks: [app-net]  
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  init-migrations:
    image: migrate/migrate:v4.18.2
    container_name: init-migrations
    networks: [app-net]
    depends_on:
      postgre:
        condition: service_healthy
    restart: no
    volumes:
      - ../migrations:/migrations:ro
    command: ["-path", "/migrations", "-database", "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgre:${DB_PORT}/${DB_NAME}?sslmode=disable","up"]

  wms:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.wms
    container_name: wms
    networks: [app-net]  
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      postgre:
        condition: service_healthy
      init-migrations:                  
        condition: service_completed_successfully
      init-kafka:
        condition: service_completed_successfully
      init-schema:                      
        condition: service_completed_successfully
    command: ["/bin/management"]

  bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.bot
    container_name: bot
    networks: [app-net]  
    env_file:
      - .env
    ports:
      - "${BOT_PORT}:8081"
    depends_on:
      wms:
        condition: service_started
    command: ["/bin/bot"]

  kafka-1:
    image: apache/kafka:4.0.2
    container_name: kafka-1
    hostname: kafka-1
    networks: [app-net]  
    ports:
      - "${KAFKA_1_PORT}:19092"
    environment:
      # Cluster
      CLUSTER_ID: "10a5cca0-8a3c-4626-b3ad-ad8f2f5326f8"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"

      # Node 
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Listeners 
      KAFKA_LISTENERS: "INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-1:9092,EXTERNAL://kafka-1:19092"

      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}"
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";

      # Fault tolerance
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
    healthcheck:
      test: ["CMD-SHELL", '/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - kafka_1_data:/var/lib/kafka/data

  kafka-2:
    image: apache/kafka:4.0.2
    container_name: kafka-2
    hostname: kafka-2
    networks: [app-net]  
    ports:
      - "${KAFKA_2_PORT}:19092"
    environment:
      # Cluster
      CLUSTER_ID: "10a5cca0-8a3c-4626-b3ad-ad8f2f5326f8"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"

      # Node 
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Listeners 
      KAFKA_LISTENERS: "INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-2:9092,EXTERNAL://kafka-2:19092"

      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}"
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";

      # Fault tolerance
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
    healthcheck:
      test: ["CMD-SHELL", '/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - kafka_2_data:/var/lib/kafka/data

  kafka-3:
    image: apache/kafka:4.0.2
    container_name: kafka-3
    hostname: kafka-3
    networks: [app-net]  
    ports:
      - "${KAFKA_3_PORT}:19092"
    environment:
      # Cluster
      CLUSTER_ID: "10a5cca0-8a3c-4626-b3ad-ad8f2f5326f8"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"

      # Node 
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Listener
      KAFKA_LISTENERS: "INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-3:9092,EXTERNAL://kafka-3:19092"

      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}"
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";

      # Fault tolerance
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: false
    healthcheck:
      test: ["CMD-SHELL", '/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - kafka_3_data:/var/lib/kafka/data

  init-kafka:
    image: apache/kafka:4.0.2
    container_name: init-kafka
    networks: [app-net]  
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}
    restart: no
    volumes:
      - ./scripts/init_kafka.sh:/opt/init_kafka.sh:ro
    entrypoint: ["/bin/bash", "/opt/init_kafka.sh"]

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    networks: [app-net]  
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      init-kafka:
        condition: service_completed_successfully

  init-schema:
    image: curlimages/curl:8.13.0
    container_name: init-schema
    networks: [app-net]
    depends_on:
      schema-registry:
        condition: service_healthy
    restart: no
    environment:
      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
    volumes:
      - ./schemas:/schemas:ro
      - ./scripts/init_schema.sh:/init_schema.sh:ro
    entrypoint: ["/bin/sh", "/init_schema.sh"]

  schema-registry:
    image: confluentinc/cp-schema-registry:8.2.0
    container_name: schema-registry
    networks: [app-net]  
    depends_on:
      kafka-1:
        condition: service_healthy  
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    ports:
      - "${SCHEMA_REGISTRY_PORT}:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: "schemas"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/subjects || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  pg_data:
  kafka_1_data:
  kafka_2_data:
  kafka_3_data:   

networks:
  app-net:
    driver: bridge