FROM golang:1.26-alpine AS builder

WORKDIR /build

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY . .
RUN go build -p=2 -o /build/management ./cmd/management

FROM alpine:latest AS runtime

COPY --from=builder /build/management /bin/management

CMD ["/bin/management"]
