FROM golang:1.26-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -p=2 -o /build/bot ./cmd/bot

FROM alpine:latest AS runtime

COPY --from=builder /build/bot /bin/bot

CMD ["/bin/bot"]
